name: Comment Check
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: "I acknowledge that I am merging in code during a code freeze"
          reaction: check
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - run: "echo Found it!"
        if: steps.check.outputs.triggered == 'true'
