name: Code Freeze and Comment Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited, closed]
  issue_comment:
    types: [created]

jobs:
  check-for-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"

      - name: Install npm v9
        shell: bash
        run: npm i -g npm@9.2.0

      - name: Install deps
        run: npm ci

      - name: Check if code freeze
        id: codefreeze
        run: node .github/scripts/check-for-codefreeze.js

  check-comment:
    needs: check-for-freeze
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Check for specific comment
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: "SPECIFIC COMMENT"
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pass if specific comment found
        run: exit 0
        if: steps.check.outputs.triggered == 'true'
