name: Check for Code Freeze

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check Freeze
        id: codefreeze
        run: node .github/scripts/check-for-codefreeze.js

      - name: Add label
        if: ${{ steps.codefreeze.outputs.isInFreeze == 'true' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Failed Codefreeze Check']
            })

      - name: Add comment
        if: ${{ steps.codefreeze.outputs.isInFreeze == 'true' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'This PR failed the code freeze check. To merge it, please remove the "Failed Codefreeze Check" label.'
            })
